// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsMIv1IvchGWiSC7oJpUSO91LUSRLpGmI',
    appId: '1:870496309646:web:745d07d0c69e7d1af354df',
    messagingSenderId: '870496309646',
    projectId: 'cloneproject-6895d',
    authDomain: 'cloneproject-6895d.firebaseapp.com',
    storageBucket: 'cloneproject-6895d.appspot.com',
    measurementId: 'G-W50G4JR1H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSxZaPyB6yPVG-CSW2GxtmkwWB4-t1ffI',
    appId: '1:870496309646:android:7f5b2127d168f296f354df',
    messagingSenderId: '870496309646',
    projectId: 'cloneproject-6895d',
    storageBucket: 'cloneproject-6895d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF8Ha2pzURYanhpPzCScgta6TQsWsC9Fw',
    appId: '1:870496309646:ios:f2eda2430649a51cf354df',
    messagingSenderId: '870496309646',
    projectId: 'cloneproject-6895d',
    storageBucket: 'cloneproject-6895d.appspot.com',
    iosClientId: '870496309646-lphhr4a0ccn5ghelgkrp9424ur1d2kub.apps.googleusercontent.com',
    iosBundleId: 'com.app.flutproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF8Ha2pzURYanhpPzCScgta6TQsWsC9Fw',
    appId: '1:870496309646:ios:f2eda2430649a51cf354df',
    messagingSenderId: '870496309646',
    projectId: 'cloneproject-6895d',
    storageBucket: 'cloneproject-6895d.appspot.com',
    iosClientId: '870496309646-lphhr4a0ccn5ghelgkrp9424ur1d2kub.apps.googleusercontent.com',
    iosBundleId: 'com.app.flutproject',
  );
}
